import type { Metadata } from 'next'
import { Inter, JetBrains_Mono, Press_Start_2P } from 'next/font/google'
import './globals.css'

/* Your custom styles go here */

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: '400'
});
const pressStart = Press_Start_2P({
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pressStart.className}>{children}</body>
    </html>
  )
}
